### ISSUE TITLE
Large images OoM errors

### ISSUE THREAD

**Issue by bluusun** [brycedrennan/imaginAIry#262]
On 24GB NVIDIA 3090 card if I go ONE(!) pixel above 768 width I get this, what hardware will work for the large image generation?

> imagine "a flower" -w 1920 -h 1080
Received 1 prompt(s) and 0 input image(s). Will repeat the generations 1 times to create 1 images.
Generating   1/1: "a flower" 1920x1080px negative-prompt:"Ugly, duplication, duplicates, mutilation, deformed, mutilated, mutation, twisted body, disfigured, bad anatomy, out of frame, extra fingers, mutated hands, poorly drawn hands, extra limbs, malformed limbs, missing arms, extra arms, missing legs, extra legs, mutated hands, extra hands, fused fingers, missing fingers, extra fingers, long neck, small head, closed eyes, rolling eyes, weird eyes, smudged face, blurred face, poorly drawn face, mutation, mutilation, cloned face, strange mouth, grainy, blurred, blurry, writing, calligraphy, signature, text, watermark, bad art," seed:813847340 prompt-strength:7.5 steps:15 sampler-type:k_dpmpp_2m
100%|| 15/15 [00:01<00:00,  7.59it/s]7.84it/s]7.83it/s]                                                                                                                           0%|                                                                                                                                                    | 0/10 [00:00<?, ?it/s]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 160.00 MiB (GPU 0; 23.70 GiB total capacity; 4.42 GiB already allocated; 137.38 MiB free; 4.49 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by brycedrennan** [comment]
well that's disappointing. easily works on my 11gb 2090. Can go much larger as well.  You sure nothing else was using gpu at the time? Can you run it outside the imaginairy shell so we get the full stack trace?

**Comment by brycedrennan** [comment]
do you have xformers installed? 10.0 has xformers as a dependency now.

**Comment by bluusun** [comment]
Take that back - ran now just fine but outputs is ...well a bit underwhelming

https://transfer.sh/H8eoIl/3.jpg

![3](https://user-images.githubusercontent.com/65051271/219974140-01bf902b-afc7-4c9e-af8c-b3619fa86306.jpg)

Sphinx at Pyramids of Giza (Egypt), tourist attraction, overlook, perfect light, beautiful, stunning, travel picture

**Comment by bluusun** [comment]
Tried more prompts but it somehow always blurred.

![8](https://user-images.githubusercontent.com/65051271/219975227-1ef129cf-6439-48c2-9e15-709e276d5ca6.jpg)

**Comment by bluusun** [comment]
This is the 'regular' output (upscaled). 
![9](https://user-images.githubusercontent.com/65051271/219975343-5bb29513-d8b7-4b1a-ab02-59f60d56a623.jpg)

**Comment by bluusun** [comment]
Related question - most of the time when I use imaginairy the produced jpgs (even upscaled) are small files (40kB), now I get 2048x2048 and about 450kB) with this command - what am I missing?

imagine "Lively sunny landscape of an egyptian village realistic detailed digital art by Maxwell Boas Jessica Rossier Christian Dimitrov Anton Fadeev trending on Artstation CGSociety rendered in Unreal Engine 4k HQ" -w 768 -r5 --upscale --model SD-2.1 --steps 100

![11](https://user-images.githubusercontent.com/65051271/219975777-147c2e44-192d-45cc-a265-b476a831eec6.jpg)

**Comment by brycedrennan** [comment]
Those blurry images look like the "composition" images, not the final image. Something is wrong. I'd like to see the entire terminal output after you run the command to understand better.

**Comment by brycedrennan** [comment]
The final image is in "generated"

**Comment by bluusun** [comment]
OK, will send soon - why is the filesize in upscaled directory so different for identical prompt on different machines?

**Comment by bluusun** [comment]
I have trouble saving the upscaled image in Python especially - i.e. 

 prompts = [
        ImaginePrompt(pp,
            upscale=True,
            width=768,
            height=512,
            init_image=LazyLoadingImage(filepath=room_local),
            init_image_strength=0.29,
            model="SD-2.1",
            steps=80
        ) ]

        for result in imagine(prompts):
            filename = uuid.uuid4()
            filename_f = f"{filename}.jpg"
            result.save(f"{img_out_folder}/{filename_f}")

Seems to save the smaller image (not upscaled)

**Comment by bluusun** [comment]
Got the full size images to work now. Generated/ Upscaled is the right folder :)

**Comment by bluusun** [comment]
Still struggling to get the Upscaled version extracted with Python :(

**Comment by bluusun** [comment]
Is there any good way to save an upscaled image with Python?

I can see how the Upscaling runs (upscale=True,) but the resulting image saved in Python is not upscaled with the below code. How can I access it? (not a Python aficionado and it works for me in command line)

So far it seems this catches:

for result in imagine(prompts):
    # do something
    result.save("my_image.jpg")

# or

imagine_image_files(prompts, outdir="./my-art")

**Comment by brycedrennan** [comment]
apologies for not responding sooner. `result.images["upscaled"]`

**Comment by brycedrennan** [comment]
I think all questions are answered here. Let me know if otherwise.
